## Full guide available at https://relay.sh/docs/getting-started

apiVersion: v1
parameters:
  id:
    default: ""
  last_updated:
    default: ""
  event_type:
    default: ""
  title:
    default: ""
  date:
    default: ""
  body:
    default: ""
  host:
    default: ""
triggers:
- name: datadog-event
  source:
    type: webhook
    image: relaysh/datadog-trigger-event-fired
  binding:
    key: !Data id
    parameters:
      id: !Data id
      last_updated: !Data last_updated
      event_type: !Data event_type
      title: !Data title
      date: !Data date
      body: !Data body
      host: !Data host
steps:
- name: echo
  image: relaysh/stdlib-step-echo
  spec:
    message: "testing that this workflow has been called from another workflow with owen"
- name: notify-workflow
  image: relaysh/slack-step-message-send
  spec:
    connection:
      !Connection { type: slack, name: relaysh-ir-bot }
    channel: "#automation-notices"
    username: puppet-disk-cleanup
    message: ":octagonal_sign: Detected high disk usage - Approve
      <https://app.relay.sh/workflows/pe-self-healing/preview|auto remediation
      workflow here> :octagonal_sign:"
#- name: approval
#  type: approval
#  description: "Wait for approval to run task-updated version"
- name: update-event-timeline
  image: relaysh/datadog-step-event-post
  spec:
    connection:
      !Connection { type: "datadog", name: "my-datadog-keys" }
    event_title: "Relay Disk Cleanup"
    event_text:
      !Fn.concat [ "Ran disk cleanup task on ", !Parameter host ]
    event_type: "info"
  #dependsOn: approval
- name: aws-ec2-step-instances-reboot
  image: relaysh/aws-ec2-step-instances-reboot
  spec:
    aws:
      connection: ${connections['aws']['my-aws-account']}
      region: us-east-1
    instanceIDs:
    - "i-015622d175284e7d4"
  #dependsOn: approval

# - name: wait-for-task
#   image: relaysh/puppet-step-run-wait
#   spec:
#     connection:
#       !Connection { type: puppet, name: relay-hydra }
#     id:
#       !Output [ run-disk-cleanup-with-PE, id ]
# - name: notify-remediation
#   image: relaysh/slack-step-message-send
#   dependsOn: run-disk-cleanup-with-PE
#   spec:
#     connection:
#       !Connection { type: slack, name: relaysh-ir-bot }
#     channel: "#automation-notices"
#     username: puppet-disk-cleanup
#     message:
#       !Fn.concat [
#         ":octagonal_sign: Detected high disk usage - Ran disk cleanup on: ",
#         !Parameter host
#       ]
# - name: run-disk-cleanup-with-PE
#   image: relaysh/puppet-step-task-run-start
#   spec:
#     connection:
#       !Connection { type: puppet, name: relaydemo-hydra }
#     scope:
#       nodes:
#       - "relaydemonix0.classroom.puppet.com"
#     params:
#       days: 3
#     noop: false
#     environment: production
#     name: disk::cleanuplogs_linux
#   dependsOn: approval
